# Document: https://docs.travis-ci.com/user/deployment
# Document Heroku: https://devcenter.heroku.com/articles/build-docker-images-heroku-yml

sudo: required
language: node_js
cache:
  directories:
    - node_modules

notifications:
  email:
    on_failure: change

node_js:
  - '13'

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.16.1

before_install:
  # import heroku CLI
  # add heroku auth:token to TravisCI Environment Variables (https://travis-ci.org/github/thuydx98/human-resource-management/settings)
  - echo 'PATH="/usr/local/heroku/bin:$PATH"' >> ~/.profile

script:
  - docker-compose up -d
  - docker ps -a

after_success:
  # - docker login -u thuydx.9598@gmail.com -p 5abd0ac2-7de7-4a25-a38b-c5405882bf0c registry.heroku.com
  # - echo 5abd0ac2-7de7-4a25-a38b-c5405882bf0c | docker login -u thuydx.9598@gmail.com --password-stdin registry.heroku.com
  - heroku container:login
  - docker tag hrm-ute registry.heroku.com/hrm-ute/web
  - docker push registry.heroku.com/hrm-ute/web
  - heroku container:release web --app hrm-ute
# deploy:
#   provider: heroku
# app: hrm-ute
# script:
# - heroku container:login
# - docker tag hrm-ute registry.heroku.com/hrm-ute/web
# - docker push registry.heroku.com/hrm-ute/web
# - heroku container:release web --app hrm-ute
# api_key:
#   secure: XruTpncq9tNODL3B7KONaYEg+SyzEGSkHOTvG4HbVBf6zbmRHyQQfEq92oItIb/h4HKZNWcy11NfEHvnDexVkFPVUo0oEIt35/W5gWgWcvqTrFp3uw7ThYb2ojAZYzwzMqrShHl2aJXoqh8JVWq9lS9lmbiOUWh9TltqBPbLl0CiIZUGtSbKjvyCuNqxYTd+Gi9g/hOfe7m0rwvIxMaw1zlYhk2icJJC9kj4jFSpU22hMM6Itw92OgZn+TpeZv8wKaDrkzMbRbicxOKRn2KZIHdOPISt3w7WqZOpY5N7KL/1yy5RUTD4RE2BLL+zrPWWlNswqPYH00SxjvmL7z096QsmCqxOocXASlb1A27eetbZmSSNP6byEFEOHHEQLCB9kLGuzEN8Hl2ar5JhUxZZBx9V/s+TQX+kR9xKtOSPCWFpqClBeTLJV1tV6gS2Udnpo7P/ldDZ5uek8tftjL/CSnGjDsTh0rOSozINI0K8ZSUzBzKZxCDPgmnInXnPbSJI3ySrQca56LtbJWsuX+5vBXqnD1+umerqU0Ab1gdaPwIY98za+Rq3PNQkYQ8RWYfnsoa+jw6qbhUgiawCpIja2yTPWShH2woi31/7PTWtPPQ5cY0N/a29qcapg8NjTcqIbeixH8Pa9kl8bnxSOpQCxvhuusI7xe3GEcFquJ/1gAk=
# run:
# - heroku container:login
# - docker tag hrm-ute registry.heroku.com/hrm-ute/web
# - docker push registry.heroku.com/hrm-ute/web
# - heroku container:release web --app hrm-ute
