version: "3.7"

services:

  # web:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: hrm-ute-container
    image: hrm-ute
    networks:
      - hrm-frontend-prod-network
    ports:
      - '80:80'
      - '433:433'
    env_file:
     - ./.env
    environment:
    - PORT=80
    - PORT=433
    - NODE_ENV=production
    - API_URI=http://localhost:10000/api
    restart: unless-stopped

networks:
  hrm-frontend-prod-network:
    driver: bridge